import HomeImg from '../assets/cimg/hero.png'
import Features from '../assets/cimg/features.png'
import CTA from '../assets/cimg/cta.png'
import Pricing from '../assets/cimg/pricing.png'
import About from '../assets/cimg/About.png'


export const componentSections = [
    {
    name: "AI Interfaces",
    route:"ai",
    count: 3,
    image: "/images/ai-placeholder.png",
    badge: "Neural",
  },
  {
    name: "Industry Dashboards",
    route:"dashboards",
    count: 3,
    image: "/images/dashboard-placeholder.png",
    badge: "Futuristic",
  },
   {
    name: "Hero Sections",
    route:"hero",
    count: 12,
    image: HomeImg,
    badge: "New",
  },
  {
    name: "Feature Sections",
    route:"feature",
    count: 20,
    image: Features,
    badge: "New",
  },
  {
    name: "CTA Sections",
    route:"CTA",
    count: 11,
    image: CTA,
    badge: "Updated",
  },
  {
    name: "Contact Sections",
    route:"Contact",
    count: 3,
    image: "/images/bento-placeholder.png",
    badge: "New",
  },
  {
    name: "Pricing Sections",
    route:"pricing",
    count: 9,
    image: Pricing,
    badge: "New",
  },
  {
    name: "About Us Sections",
    route:"about",
    count: 8,
    image: About,
    badge: "New",
  },
  {
    name: "Banner Sections",
    route:"Banner",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Blog Sections",
    route:"Blog",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "404 Sections",
    route:"Error",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "FAQ Sections",
    route:"FAQ",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Footer Section",
    route:"Footer",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Logocolud Section",
    route:"Logocolud",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Navbar ",
    route:"Navbar",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "News letter",
    route:"News",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Process Section",
    route:"Process",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Project Section",
    route:"Project",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Services Section",
    route:"Services",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Stats Section",
    route:"Stats",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Swipper Section",
    route:"Swipper",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Team Section",
    route:"Team",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Testimonial",
    route:"Testimonial",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Whychoose",
    route:"Whychoose",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
  {
    name: "Sign-Signup",
    route:"Sign-Signup",
    count: 8,
    image: "/images/about-placeholder.png",
    badge: "New",
  },
 
];